// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgMhDvN13vDP9ETsgZMj7qZWyl0I24T50',
    appId: '1:894546526719:web:08158533cd45f4ce4927ca',
    messagingSenderId: '894546526719',
    projectId: 'demofcm-eb234',
    authDomain: 'demofcm-eb234.firebaseapp.com',
    storageBucket: 'demofcm-eb234.appspot.com',
    measurementId: 'G-GFVQHVB8TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOPHwWP2-3A0oCevOzJfgc33-S1BQOX9A',
    appId: '1:894546526719:android:fd43801154c66b7e4927ca',
    messagingSenderId: '894546526719',
    projectId: 'demofcm-eb234',
    storageBucket: 'demofcm-eb234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCXLGqhcCGvcm4UtHjFw_l9GaQdDb9esA',
    appId: '1:894546526719:ios:073b3db8d445e9ec4927ca',
    messagingSenderId: '894546526719',
    projectId: 'demofcm-eb234',
    storageBucket: 'demofcm-eb234.appspot.com',
    iosClientId: '894546526719-v42u2rmao7rc4jnve6l9gm3rviglh8u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoPushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCXLGqhcCGvcm4UtHjFw_l9GaQdDb9esA',
    appId: '1:894546526719:ios:073b3db8d445e9ec4927ca',
    messagingSenderId: '894546526719',
    projectId: 'demofcm-eb234',
    storageBucket: 'demofcm-eb234.appspot.com',
    iosClientId: '894546526719-v42u2rmao7rc4jnve6l9gm3rviglh8u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoPushNotification',
  );
}
